
# Entubamiento de un conjunto de datos asociado a su proyecto

## Desarrollador por:

Luis Octavio González Salcedo

Diplomado en Inteligencia Artificial % Aprendizaje Profundo


## 1. Importaciones de librerías

Se requieren importar las siguientes librerías:

**TensorFlow**: librería Python para computación numérica rápida.  También es una librería que puede utilizarse para crear modelos de Deep Learning directamente o utilizando librerías de envolturas que simplifican el proceso construido sobre TensorFlow.

**NumPy**: biblioteca para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

**pathlib**: Es un módulo que ofrece clases que representan rutas del sistema de archivos con semántica apropiada para diferentes sistemas operativos. Las clases de ruta se dividen entre rutas puras , que proporcionan operaciones puramente computacionales sin Entradas / Salidas, y rutas concretas, que heredan de rutas puras pero también proporcionan operaciones de Entrada / Salida. Crea una instancia de una ruta concreta para la plataforma en la que se ejecuta el código. Los caminos puros son útiles en algunos casos especiales; por ejemplo: 1.- Si desea manipular las rutas de Windows en una máquina Unix (o viceversa). No puede crear una instancia de un WindowsPathcuando se ejecuta en Unix, pero puede crear una instancia PureWindowsPath; 2.- Desea asegurarse de que su código solo manipule rutas sin acceder al sistema operativo. En este caso, la instanciación de una de las clases puras puede ser útil, ya que simplemente no tienen operaciones de acceso al sistema operativo. [[1]](https://docs.python.org/3/library/pathlib.html).

**os**: Este módulo os proporciona un contenedor para módulos específicos de la plataforma, tales como posix, nt y mac. La interfaz de programación para las funciones disponibles en todas las plataformas debe ser la misma, por lo que usar el módulo os ofrece cierta medida de portabilidad. Sin embargo, no todas las funciones están disponibles en todas las plataformas. Muchas de las funciones de gestión de procesos descritas no están disponibles para Windows. [[2]](https://rico-schmidt.name/pymotw-3/os/).

**pandas**:  Pandas es una herramienta de manipulación y análisis de datos de código abierto rápida, potente, flexible y fácil de usar, construida sobre el lenguaje de programación Python . [[3]](https://pandas.pydata.org/).


**matplotlib**: Matplotlib es una biblioteca completa para crear visualizaciones estáticas, animadas e interactivas en Python. [[4]](https://matplotlib.org/).

In [1]:

import tensorflow as tf ##importación de tensorflow

import pathlib ##importación del módulo pathlib
import os ##importación del módulo os
import matplotlib.pyplot as plt ##importación de matplotlib
import pandas as pd ##importación de pandas
import numpy as np ##importación de numpy

##configura las opciones de impresión
##Estas opciones determinan la forma en que se muestran los números de punto flotante, las matrices y otros objetos NumPy.
##En este caso, usa el parámetro de precisión, que corresponde al número de dígitos de precisión para salida de punto flotante.
np.set_printoptions(precision=4)


## 2. Consumir datos CSV

El formato de archivo CSV es un formato popular para almacenar datos tabulares en texto sin formato.

Por ejemplo, lo haremos con el archivo que contiene el conjunto de datos del proyecto.


La base de datos tomada para el taller corresponde a la almacenada en el archivo base_datos_mezclas.csv. Este conjunto de datos contiene reportes de diseños de mezclas (dosificaciones de mezclas) de hormigón. Las mezclas de hormigón allí reportadas han sido recopiladas de reportes consultados en artículos de revistas, documentos finales de trabajos de grado y tesis, e informes técnicos. Los reportes incluyen diseños de mezlcas de hormigón que no incluyen e incluyen fibras de acero, como material reforzante de la matriz cementicia.

Cada registro del conjunto de datos, originalmente reporta el tipo y cantidad de los materiales utilizados, y en algunos casos la clase o calidad del tipo de material. El conjunto de datos del proyecto, se elaboró a partir no solo de las cantidades sino también a partir de diversas relaciones de los materiales, en razón a que experiencias previas de entrenamiento de redes neuronales artificiales (redes multicapas de backpropagation) mostraron mejores resultados en estas redes y en otras (redes de funciones de base radial) cuando el conjunto de entrenamiento se presentó de esta manera, y donde las variables cualitativas se representaron de manera jerárquica [5](https://www.redalyc.org/jatsRepo/911/91163366005/91163366005.pdf).

El conjunto de datos contiene valores para las siguientes variables (El conjunto de datos se ha conformado con 626 registros, cuyas variables son: "No.", "C_Kg/m3", "C-1", "C-2", "C-3", "C-4", "SF/binder", "FA/binder", "GBFS/binder", "puzolana/binder", "(W+HWR)/binder", "HWR/binder", HWR-P", "HWR-SP", "(W+HWR)/sólidos", "S/(S+G)", "T-S", "(S+G)/binder)", "T-G", "G-TMA_mm", "LTCA", "AEA/binder", "Vf", "T-SFR", "Lf_mm", "Lf/Df", "fc_MPa"), que se describen a continuación (las unidades para cantidades se expresan con relación a un metro cúbico de hormigón elaborado):


No., corresponde al número de registro (no está explícito en el conjunto de datos, sin embargo, en la carga del archivo e impresión, la tabla lo muestra).

C_Kg/m3, corresponde a la cantidad de cemento, y se expresa en Kg/m^3

C-1, corresponde a uso de cemento de uso general (Tipo I)

C-2, corresponde a uso de cemento para acción moderada al sulfato y calor moderado a la hidratación, y bajo calor a la hidratación (Tipo II y Tipo IV, respectivamente)

C-3, corresponde a uso de cemento para resistencia altas a temprana edad (Tipo III)

C-4, corresponde a uso de cemento para alta resistencia a los sulfatos (Tipo V)

SF/binder, corresponde a la relación (cantidad de humo de sílice) / (cantidad de material cementante)

FA/binder, corresponde a la relación (cantidad de cenizas volante) / (cantidad de material cementante)

GBFS/binder, corresponde a la relación (cantidad escorias) / (cantidad de material cementante)

puzolana/binder, corresponde a la relación (cantidad de material puzolánico) / (cantidad de material cementante)

(W+HWR)/binder, corresponde a la relación (cantidades de de agua y agente retenedor de agua) /(cantidad de material cementante)

HWR/binder, corresponde a la relación (cantidad de agente renetedor de agua) / (cantidad de material cementante)

HWR-P, corresponde a uso de agente retenedor de agua tipo plastificante

HWR-SP, corresponde a uso de agente retenedor de agua tipo superplastificante

(W+HWR)/sólidos, corresponde a la relación (cantidades de agua y agente retenedor de agua) / (cantidad de material sólido)

S/(S+G), corresponde a la relación (cantidad de agregado fino) / (cantidad de agregados)

T-S, corresponde al origen de extracción del agregado fino

(S+G)/binder), corresponde a la relación (cantidad de agregado) / (cantidad de material cementante)

T-G, corresponde al origen de extracción del agregado grueso

G-TMA_mm, corresponde al tamaño máximo del agregado grueso, expresado en mm

LTCA, corresponde al tipo de perfil litológico del agrefado grueso, es decir origen geológico

AEA/binder, corresponde a la relación (cantidad de agente entrador de aire) /(cantidad de material cementante)

Vf, corresponde a la cantidad de fibra metálica, expresada en fracción de volumen

T-SFR, corresponde al tipo de fibra metálica

Lf_mm, corresponde a la longitud de la fibra metálica

Lf/Df, corresponde a la relación de aspecto de la fibra, lo cual es la relación entre su logitud y su diámetro equivalente

fc_MPa, corresponde a la resistencia de diseño a la compresión, del hormigón en estado endurecido, y obtenido a partir de una dosificación de materia prima consistente en cemento, agua, humo de sílice, cenizas volantes, escoria, arena, grava, agente retenedor de agua, agente inclusor de aire, y fibra metálica, así como algunos atributos de la materia prima. Esta variable se expresa en MPa.

In [2]:

from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

In [3]:

os.getcwd() ##Se visualiza donde está ubicado el directorio de trabajo

'C:\\Users\\Usuario\\Desktop\\luis octavio gonzalez\\Curso DIplomado IA & AP\\Repositorio Curso\\Diplomado\\Temas\\Fundamentos\\Cuadernos'

In [4]:
##Se carga el conjunto de datos en la variable B
B = 'base_datos_mezclas.csv'
data = pd.read_csv(B, header=0, sep=';')
print(data.shape)
data.head()

(626, 26)

,C_Kg/m3,C-1,C-2,C-3,C-4,SF/ binder,FA/binder,GBFS/binder,puzolana/binder,(W+HWR)/binder,...,(S+G)/binder,T-G,G-TMA_mm,LTCA,AEA/binder,Vf,T-SFR,Lf_mm,Lf/Df,fc_MPa
0,308.40,1,0,0,0,0.0,0.200,0.0,0.200,0.4500,...,8.4047,1.0,10.0,1.0,0.0,0.00,0.0,0.0,0.0,15.56
1,318.04,1,0,0,0,0.0,0.175,0.0,0.175,0.4638,...,8.4047,1.0,10.0,1.0,0.0,0.00,0.0,0.0,0.0,16.44
2,308.40,1,0,0,0,0.0,0.200,0.0,0.200,0.4500,...,8.4047,1.0,10.0,1.0,0.0,0.25,1.0,30.0,50.0,16.44
3,308.40,1,0,0,0,0.0,0.200,0.0,0.200,0.4500,...,8.4047,1.0,10.0,1.0,0.0,0.50,1.0,30.0,50.0,16.44
4,308.40,1,0,0,0,0.0,0.200,0.0,0.200,0.4500,...,8.4047,1.0,10.0,1.0,0.0,0.75,1.0,30.0,50.0,16.89


## 3. Eliminación de Registros Faltantes


Se hace una revisión de registros faltantes. Siendo la variable de estudio "f'c" se hace necesario eliminar los registros que tengan faltantes en "f'c", y que corresponden a los que tienen el valor de NA en dicho valor.

In [5]:

##Se eliminan los registros "f'c" que son faltantes, es decir con valor NA
data_no_NA = data[pd.notnull(data['fc_MPa'])]
print(data_no_NA.shape)
data_no_NA.head()
##Para crear un nuevo archivo extensión .csv, que no contiene registros NA, se puede activar la siguiente línea:
##data_no_NA.to_csv("data_no_NA.csv")

(626, 26)

,C_Kg/m3,C-1,C-2,C-3,C-4,SF/ binder,FA/binder,GBFS/binder,puzolana/binder,(W+HWR)/binder,...,(S+G)/binder,T-G,G-TMA_mm,LTCA,AEA/binder,Vf,T-SFR,Lf_mm,Lf/Df,fc_MPa
0,308.40,1,0,0,0,0.0,0.200,0.0,0.200,0.4500,...,8.4047,1.0,10.0,1.0,0.0,0.00,0.0,0.0,0.0,15.56
1,318.04,1,0,0,0,0.0,0.175,0.0,0.175,0.4638,...,8.4047,1.0,10.0,1.0,0.0,0.00,0.0,0.0,0.0,16.44
2,308.40,1,0,0,0,0.0,0.200,0.0,0.200,0.4500,...,8.4047,1.0,10.0,1.0,0.0,0.25,1.0,30.0,50.0,16.44
3,308.40,1,0,0,0,0.0,0.200,0.0,0.200,0.4500,...,8.4047,1.0,10.0,1.0,0.0,0.50,1.0,30.0,50.0,16.44
4,308.40,1,0,0,0,0.0,0.200,0.0,0.200,0.4500,...,8.4047,1.0,10.0,1.0,0.0,0.75,1.0,30.0,50.0,16.89


## 4. Compresión de los datos

### Decisión sobre la columna objetivo

Con el conjunto de datos procesados y explorados, es necesario crear una matriz de variables independientes y un vector de variables dependientes. En primer lugar,  se debes decidir qué columna utilizar como columna de destino para el modelado en función de la pregunta que deseas responder.

Como la columna destino se crean la matriz de variable independiente, y el vector de las variables dependientes con solo los datos de la última columna. Esto se logra con el siguiente código:

In [6]:
##Creación de la matriz de variables independientes:
X = data.iloc[:, :-1]. values

##Creación del vector de variables dependientes:
Y = data.iloc[:, -1].values

In [8]:

print(X.shape)
X

(626, 25)

array([[3.0840e+02, 1.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [3.1804e+02, 1.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [3.0840e+02, 1.0000e+00, 0.0000e+00, ..., 1.0000e+00, 3.0000e+01,
        5.0000e+01],
       ...,
       [6.7700e+02, 1.0000e+00, 0.0000e+00, ..., 2.5000e-01, 1.6000e+01,
        8.9000e+01],
       [6.7700e+02, 1.0000e+00, 0.0000e+00, ..., 2.5000e-01, 6.0000e+00,
        3.3000e+01],
       [6.7700e+02, 1.0000e+00, 0.0000e+00, ..., 2.5000e-01, 6.0000e+00,
        3.3000e+01]])

In [9]:

X = np.delete(X, (0,1), axis=1)
print(X.shape)
print(X)

(626, 23)
[[ 0.    0.    0.   ...  0.    0.    0.  ]
 [ 0.    0.    0.   ...  0.    0.    0.  ]
 [ 0.    0.    0.   ...  1.   30.   50.  ]
 ...
 [ 0.    0.    0.   ...  0.25 16.   89.  ]
 [ 0.    0.    0.   ...  0.25  6.   33.  ]
 [ 0.    0.    0.   ...  0.25  6.   33.  ]]

In [10]:

print(Y.shape)
Y

(626,)

array([ 15.56,  16.44,  16.44,  16.44,  16.89,  17.33,  17.33,  17.33,
        17.78,  17.78,  18.22,  18.22,  18.22,  18.67,  20.  ,  20.04,
        21.67,  21.74,  22.22,  24.15,  25.33,  25.33,  25.33,  26.22,
        26.65,  26.67,  26.67,  26.69,  27.1 ,  27.56,  27.56,  27.83,
        27.9 ,  27.96,  28.  ,  28.  ,  28.  ,  28.16,  28.18,  28.27,
        28.5 ,  28.86,  28.88,  29.12,  30.  ,  30.14,  30.2 ,  30.2 ,
        30.4 ,  30.42,  30.5 ,  30.5 ,  30.6 ,  30.7 ,  30.74,  30.8 ,
        31.03,  31.06,  31.1 ,  31.11,  31.11,  31.2 ,  31.47,  31.5 ,
        31.5 ,  31.5 ,  31.7 ,  31.7 ,  31.8 ,  32.  ,  32.1 ,  32.2 ,
        32.3 ,  32.3 ,  32.41,  32.41,  32.5 ,  32.5 ,  32.6 ,  32.6 ,
        32.6 ,  32.6 ,  32.9 ,  32.9 ,  33.  ,  33.1 ,  33.2 ,  33.2 ,
        33.3 ,  33.3 ,  33.31,  33.33,  33.5 ,  33.6 ,  33.7 ,  33.77,
        33.77,  33.79,  33.79,  33.9 ,  33.9 ,  34.2 ,  34.2 ,  34.22,
        34.4 ,  34.48,  34.67,  34.67,  34.9 ,  35.  ,  35.  ,  35.  ,
        35.11,  35.13,  35.17,  35.3 ,  35.3 ,  35.4 ,  35.4 ,  35.5 ,
        35.5 ,  35.56,  35.56,  35.8 ,  35.86,  35.9 ,  36.1 ,  36.1 ,
        36.2 ,  36.21,  36.35,  36.4 ,  36.44,  36.5 ,  36.55,  36.62,
        36.7 ,  36.7 ,  36.78,  36.8 ,  36.89,  36.9 ,  37.  ,  37.1 ,
        37.2 ,  37.21,  37.3 ,  37.3 ,  37.3 ,  37.33,  37.4 ,  37.5 ,
        37.5 ,  37.64,  37.7 ,  37.7 ,  37.72,  37.78,  37.78,  37.78,
        37.78,  37.8 ,  38.1 ,  38.12,  38.2 ,  38.2 ,  38.22,  38.25,
        38.3 ,  38.3 ,  38.37,  38.47,  38.5 ,  38.55,  38.67,  38.7 ,
        38.9 ,  38.96,  39.05,  39.11,  39.11,  39.11,  39.16,  39.2 ,
        39.5 ,  39.5 ,  39.5 ,  39.7 ,  39.75,  39.76,  39.78,  39.83,
        39.9 ,  39.91,  40.  ,  40.  ,  40.  ,  40.  ,  40.  ,  40.  ,
        40.  ,  40.  ,  40.  ,  40.1 ,  40.1 ,  40.1 ,  40.2 ,  40.2 ,
        40.43,  40.44,  40.44,  40.44,  40.44,  40.46,  40.65,  40.65,
        40.7 ,  40.76,  40.89,  40.89,  40.89,  41.  ,  41.03,  41.09,
        41.1 ,  41.22,  41.3 ,  41.33,  41.38,  41.4 ,  41.5 ,  41.5 ,
        41.7 ,  41.9 ,  41.97,  42.  ,  42.07,  42.1 ,  42.13,  42.16,
        42.16,  42.3 ,  42.3 ,  42.3 ,  42.4 ,  42.4 ,  42.48,  42.56,
        42.66,  42.67,  43.1 ,  43.1 ,  43.17,  43.2 ,  43.2 ,  43.26,
        43.31,  43.34,  43.34,  43.35,  43.36,  43.4 ,  43.41,  43.43,
        43.45,  43.46,  43.51,  43.52,  43.57,  43.71,  43.75,  43.75,
        43.79,  43.9 ,  43.94,  43.98,  44.  ,  44.  ,  44.33,  44.4 ,
        44.4 ,  44.5 ,  44.56,  44.57,  44.6 ,  44.76,  44.76,  44.78,
        44.78,  44.83,  44.84,  44.89,  44.92,  44.98,  45.  ,  45.01,
        45.08,  45.13,  45.16,  45.18,  45.19,  45.22,  45.22,  45.32,
        45.43,  45.47,  45.53,  45.75,  45.76,  46.05,  46.11,  46.22,
        46.22,  46.25,  46.3 ,  46.56,  46.67,  46.67,  46.8 ,  46.8 ,
        46.8 ,  46.84,  47.1 ,  47.12,  47.4 ,  47.54,  47.56,  47.56,
        47.66,  48.  ,  48.02,  48.28,  48.4 ,  48.89,  49.34,  49.4 ,
        49.6 ,  49.7 ,  50.22,  50.3 ,  50.37,  50.6 ,  50.64,  50.99,
        51.  ,  51.03,  51.3 ,  51.41,  51.5 ,  51.6 ,  51.74,  51.8 ,
        52.  ,  52.  ,  52.1 ,  52.2 ,  52.25,  52.3 ,  52.41,  52.5 ,
        52.59,  52.9 ,  53.04,  53.22,  53.3 ,  53.33,  53.35,  53.4 ,
        53.5 ,  53.63,  53.8 ,  53.9 ,  54.  ,  54.07,  54.07,  54.2 ,
        54.3 ,  54.4 ,  54.5 ,  54.8 ,  54.8 ,  54.83,  54.87,  54.9 ,
        54.9 ,  54.9 ,  55.  ,  55.1 ,  55.1 ,  55.2 ,  55.4 ,  55.5 ,
        55.6 ,  55.62,  55.65,  56.  ,  56.13,  56.2 ,  56.3 ,  56.3 ,
        56.43,  56.6 ,  56.8 ,  56.85,  57.4 ,  57.63,  57.66,  57.93,
        58.5 ,  58.5 ,  58.5 ,  59.28,  59.3 ,  59.31,  59.43,  60.  ,
        60.  ,  60.18,  60.3 ,  61.03,  61.2 ,  61.79,  61.99,  62.  ,
        62.  ,  62.1 ,  62.2 ,  62.2 ,  62.32,  62.43,  62.6 ,  62.71,
        62.8 ,  62.85,  62.9 ,  62.93,  63.  ,  63.  ,  63.03,  63.3 ,
        63.5 ,  63.6 ,  63.62,  63.9 ,  64.5 ,  64.75,  64.85,  65.  ,
        65.2 ,  65.3 ,  65.3 ,  65.43,  65.5 ,  65.7 ,  65.73,  65.8 ,
        65.92,  65.93,  65.93,  66.03,  66.12,  66.2 ,  66.21,  66.3 ,
        66.6 ,  66.7 ,  66.7 ,  66.8 ,  66.83,  66.85,  66.87,  67.  ,
        67.  ,  67.  ,  67.04,  67.1 ,  67.2 ,  67.24,  67.38,  67.5 ,
        67.72,  67.9 ,  68.  ,  68.  ,  68.  ,  68.21,  68.36,  68.5 ,
        68.55,  68.6 ,  68.6 ,  69.  ,  69.01,  69.1 ,  69.23,  69.7 ,
        69.8 ,  69.9 ,  69.9 ,  70.05,  70.35,  70.5 ,  70.6 ,  70.69,
        70.75,  71.1 ,  71.15,  71.2 ,  71.25,  71.4 ,  71.4 ,  71.58,
        71.64,  71.96,  72.  ,  72.  ,  72.15,  72.32,  72.41,  72.6 ,
        72.77,  72.94,  73.  ,  73.1 ,  73.25,  74.31,  74.63,  75.03,
        75.21,  75.7 ,  75.87,  75.9 ,  76.  ,  76.2 ,  76.2 ,  76.41,
        76.5 ,  76.96,  77.48,  77.7 ,  77.7 ,  77.8 ,  77.8 ,  77.98,
        78.  ,  78.3 ,  78.54,  79.  ,  79.2 ,  80.66,  80.74,  81.  ,
        81.1 ,  81.52,  82.1 ,  82.38,  82.83,  82.86,  82.97,  83.03,
        83.26,  83.5 ,  84.4 ,  85.1 ,  85.8 ,  85.91,  86.  ,  86.47,
        87.3 ,  87.4 ,  87.5 ,  87.7 ,  88.51,  88.9 ,  90.  ,  90.41,
        90.7 ,  90.74,  91.29,  91.38,  91.88,  92.14,  92.9 ,  94.13,
        96.9 ,  96.9 ,  97.3 ,  99.9 , 102.4 , 104.  , 105.7 , 106.2 ,
       108.  , 110.  , 110.2 , 110.7 , 111.3 , 111.6 , 112.5 , 113.  ,
       114.6 , 115.  , 120.7 , 123.1 , 126.7 , 126.7 , 126.7 , 126.88,
       129.7 , 131.48, 132.  , 143.  , 145.  , 154.  , 157.5 , 159.7 ,
       161.5 , 162.7 , 163.5 , 165.5 , 167.  , 173.8 , 184.5 , 192.5 ,
       197.  , 200.5 ])